"""
Airfoil Export Module — CSV and STEP formats.

MIT License - Copyright (c) 2025
"""

import csv
import numpy as np
from pathlib import Path


def export_csv(xu, yu, xl, yl, filepath: str, info: dict) -> Path:
    """
    Export airfoil coordinates to CSV.

    Columns: surface, x_mm, y_mm
    Upper surface from LE→TE, lower surface from LE→TE.

    Parameters
    ----------
    xu, yu  : upper surface coordinates (numpy arrays)
    xl, yl  : lower surface coordinates (numpy arrays)
    filepath: output file path (str or Path)
    info    : dict from generate_airfoil() for header metadata

    Returns
    -------
    Path of the written file.
    """
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    with open(filepath, "w", newline="") as f:
        writer = csv.writer(f)

        # Header block
        writer.writerow(["# NACA Airfoil Coordinate Export"])
        writer.writerow([f"# Series: {info.get('series', 'NACA')}"])
        writer.writerow([f"# Code: {info.get('code', '')}"])
        writer.writerow([f"# Chord: {info.get('chord_mm', '')} mm"])
        writer.writerow([f"# Points per surface: {info.get('n_points', '')}"])
        writer.writerow([f"# Generated by NACA Airfoil Generator"])
        writer.writerow([])
        writer.writerow(["surface", "x_mm", "y_mm"])

        for x, y in zip(xu, yu):
            writer.writerow(["upper", round(float(x), 6), round(float(y), 6)])
        for x, y in zip(xl, yl):
            writer.writerow(["lower", round(float(x), 6), round(float(y), 6)])

    return filepath


def export_step(xu, yu, xl, yl, filepath: str, info: dict) -> Path:
    """
    Export airfoil as a STEP file using CadQuery.

    Creates a closed 2D wire extruded 1 mm (unit thickness) for CAD import.
    The profile is in the XY plane, chord along X axis.

    Parameters
    ----------
    xu, yu  : upper surface coordinates (numpy arrays)
    xl, yl  : lower surface coordinates (numpy arrays)
    filepath: output file path (str or Path)
    info    : dict from generate_airfoil()

    Returns
    -------
    Path of the written file.
    """
    try:
        import cadquery as cq
    except ImportError:
        raise ImportError(
            "cadquery is required for STEP export. Install with: pip install cadquery"
        )

    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Build ordered closed polygon: upper LE→TE, lower TE→LE
    upper_pts = list(zip(xu.tolist(), yu.tolist()))
    lower_pts = list(zip(xl[::-1].tolist(), yl[::-1].tolist()))
    all_pts = upper_pts + lower_pts

    # Build wire from 2D points in XY plane, then extrude 1 mm for a solid body
    wire = cq.Workplane("XY").polyline(all_pts).close()
    solid = wire.extrude(1.0)  # 1 mm extrusion — thin slab for CAD import

    cq.exporters.export(solid.val(), str(filepath))

    return filepath
